<?php /* Translated by Paul (https://paul.bid) www.paul.bid@gmail.com */
return array (
  '<strong>Administration</strong>' => '<strong>Панель Управления</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Урашечки!</strong> Это всё на сегодня.',
  '<strong>Modules</strong>' => '<strong>Модули</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Будучи администратором, вы можете управлять всем сайтом отсюда — из Панели Управления.<br><br>Помимо раздела модулей, мы не будем вдаваться в подробности, так как у каждого раздела в Панели Управления есть своё краткое описание.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Слева находится основное меню Панели Управления. В частности, отсюда вы можете получить доступ к Маркетплейсу модулей для HumHub, где вы можете устанавливать любое количество модулей в пару кликов мышью.<br><br>Как уже упоминалось, модули расширяют возможности, доступные для сообществ, профилей пользователей или для всего сайта в целом.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Поздравляем, вы узнали обо всех наиболее важных функциях и настройках и готовы приступить к использованию и развитию сайта.<br><br>Мы надеемся, что вам и всем будущим пользователям понравится этот сайт. Мы с нетерпением ждём любых предложений, которые вы хотели бы направить нам для дальнейшего успешного развития нашего проекта. Также вы можете поддержать нас финансово или принять участие в разработке. Не стесняйтесь обращаться к нам на www.humhub.org.<br>Перевод HumHub на русский язык выполнил Павел Бид, мой сайт <a target="_blank" href="https://paul.bid">paul.bid</a> и моя почта www.paul.bid@gmail.com — напишите, если нашли ошибки и неточности в переводе, а также если вам нужен перевод модуля, либо перевод чего-то ещё.<br><br>Оставайтесь с нами. 😊',
);
