{
 "title": "Adaptive Overload Protection",
 "description": "Dashboard for testing various AOP scenarios.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "K6 Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "K6 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{status=~\"2[0-9]{2}\"}[5m]))\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{status=~\"503\"}[5m]))\n",
     "legendFormat": "Rejections"
    }
   ]
  },
  {
   "title": "K6 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "max(k6_http_req_duration_p99)", "legendFormat": "p99" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Vault HTTP req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (irate(vault_core_handle_login_request_count[5m])) by (instance)",
     "legendFormat": "{{instance}} login"
    },
    {
     "expr": "sum (irate(vault_core_handle_request_count[5m])) by (instance)",
     "legendFormat": "{{instance}} req"
    }
   ]
  },
  {
   "title": "Vault HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(vault_core_handle_login_request{quantile=\"0.99\",instance=~\"vault-*\"}) by (instance, quantile)",
     "legendFormat": "{{instance}} {{quantile}} login"
    },
    {
     "expr": "max(vault_core_handle_request{quantile=\"0.99\",instance=~\"vault-*\"}) by (instance, quantile)",
     "legendFormat": "{{instance}} {{quantile}}"
    },
    {
     "expr": "sum(irate(vault_core_handle_request_sum{instance=~\"vault-*\"}[5m]))by(instance)/sum(irate(vault_core_handle_request_count{instance=~\"vault-*\"}[5m]))by (instance)",
     "legendFormat": "{{instance}} mean"
    }
   ]
  },
  {
   "title": "WAL Writes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(vault_wal_flushReady_count{}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Adaptive Overload Protection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "PID Shed Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vault_wal_write_controller_reject_fraction",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PID P",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vault_wal_write_controller_p", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PID I",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vault_wal_write_controller_i", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PID D",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vault_wal_write_controller_d", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "WAL flushReady Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vault_wal_flushReady_queue_len{}",
     "legendFormat": "{{instance}} {{quantile}}"
    }
   ]
  },
  {
   "title": "WAL Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max (vault_wal_flushReady_batch_size) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "irate(vault_wal_flushReady_batch_size_sum[5m])/irate(vault_wal_flushReady_batch_size_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Batch Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max (vault_raft_boltdb_logBatchSize) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "max(irate(vault_raft_boltdb_logBatchSize_sum{instance=~\"vault-*\"}[5m])/irate(vault_raft_boltdb_logBatchSize_count{instance=~\"vault-*\"}[5m]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "targets": [
    { "expr": "vault_runtime_num_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InFlight Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vault_core_in_flight_requests", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Vault Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"vault-.*\"}[5m])) by (instance, mode)",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"vault-.*\"} - node_memory_MemFree_bytes{instance=~\"vault-.*\"} - node_memory_Buffers_bytes{instance=~\"vault-.*\"} - node_memory_Cached_bytes{instance=~\"vault-.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Flushes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(node_disk_flush_requests_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Test Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Leadership lost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "targets": [
    { "expr": "core_leadership_lost_sum", "legendFormat": "{{instance}} leadership lost" }
   ]
  },
  {
   "title": "Leases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 58 },
   "targets": [
    { "expr": "vault_expire_num_leases", "legendFormat": "{{instance}} leases" },
    {
     "expr": "vault_expire_num_irrevocable_leases",
     "legendFormat": "{{instance}} irrevocable"
    }
   ]
  },
  {
   "title": "Logshipper",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 58 },
   "targets": [
    {
     "expr": "irate(vault_logshipper_buffer_length[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "irate(vault_raft_replication_heartbeat_sum[$__rate_interval])",
     "legendFormat": "{{instance}} heartbeats"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "sum(vault_replication_wal_last_performance_wal{instance=\"127.0.0.2:8200\"}) - sum(vault_replication_fsm_last_remote_wal{instance=\"127.0.0.5:8200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 65 },
   "targets": [
    { "expr": "vault_identity_entity_count", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Raft Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Raft Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_commitTime", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_raft_commitTime_sum[5m])/irate(vault_raft_commitTime_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft Storage Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_storage_transaction", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_raft_storage_transaction_sum[5m])/irate(vault_raft_storage_transaction_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft Store Logs Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(vault_raft_rpc_appendEntries_storeLogs_sum[5m])/irate(vault_raft_rpc_appendEntries_storeLogs_count[5m])",
     "legendFormat": "Follower Store Logs {{instance}} mean"
    },
    {
     "expr": "irate(vault_raft_leader_dispatchLog_sum[5m])/irate(vault_raft_leader_dispatchLog_count[5m])",
     "legendFormat": "Leader Dispatch Logs mean"
    }
   ]
  },
  { "title": "WAL Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "WAL Persist Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_wal_persistWALs", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_wal_persistWALs_sum[5m])/irate(vault_wal_persistWALs_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Flush/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(vault_wal_persistWALs_count[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Flush Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_wal_flushReady", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_wal_flushReady_sum[5m])/irate(vault_wal_flushReady_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  { "title": "FSM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "FSM Apply Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(vault_raft_fsm_applyBatch_sum[5m])/irate(vault_raft_fsm_applyBatch_count[5m])",
     "legendFormat": "{{instance}} mean"
    }
   ]
  },
  { "title": "Client Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"k6\"}[5m])) by (instance, mode)",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"k6\"} - node_memory_MemFree_bytes{instance=\"k6\"} - node_memory_Buffers_bytes{instance=\"k6\"} - node_memory_Cached_bytes{instance=\"k6\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}