{
 "title": "Vault Write Performance",
 "time": { "from": "2023-11-08T13:01:33.986Z", "to": "2023-11-08T13:06:23.709Z" },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vault HTTP req/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (irate(vault_core_handle_request_count[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Writes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(vault_wal_flushReady_count{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Flush/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(vault_wal_persistWALs_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Ready Queue Len",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vault_wal_flushReady_queue_len{}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "irate(vault_wal_flushReady_queue_len_sum[5m])/irate(vault_wal_flushReady_queue_len_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max (vault_wal_flushReady_batch_size) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "irate(vault_wal_flushReady_batch_size_sum[5m])/irate(vault_wal_flushReady_batch_size_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft commit/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (irate(vault_raft_commitTime_count[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Vault HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(vault_core_handle_request) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg( irate(vault_core_handle_request_sum[5m])/irate(vault_core_handle_request_count[5m])) by (instance)",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Flush Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_wal_flushReady", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_wal_flushReady_sum[5m])/irate(vault_wal_flushReady_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Persist Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_wal_persistWALs", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_wal_persistWALs_sum[5m])/irate(vault_wal_persistWALs_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_commitTime", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_raft_commitTime_sum[5m])/irate(vault_raft_commitTime_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "FSM Apply Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(vault_raft_fsm_applyBatch_sum[5m])/irate(vault_raft_fsm_applyBatch_count[5m])",
     "legendFormat": "{{instance}} mean"
    }
   ]
  },
  {
   "title": "Raft Storage Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_storage_transaction", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_raft_storage_transaction_sum[5m])/irate(vault_raft_storage_transaction_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft Store Logs Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(vault_raft_rpc_appendEntries_storeLogs_sum[5m])/irate(vault_raft_rpc_appendEntries_storeLogs_count[5m])",
     "legendFormat": "Follower Store Logs {{instance}} mean"
    },
    {
     "expr": "irate(vault_raft_leader_dispatchLog_sum[5m])/irate(vault_raft_leader_dispatchLog_count[5m])",
     "legendFormat": "Leader Dispatch Logs mean"
    }
   ]
  },
  { "title": "Vault Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"vault-.*\"}[5m])) by (instance, mode)",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"vault-.*\"} - node_memory_MemFree_bytes{instance=~\"vault-.*\"} - node_memory_Buffers_bytes{instance=~\"vault-.*\"} - node_memory_Cached_bytes{instance=~\"vault-.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Flushes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(node_disk_flush_requests_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"vault-.*\",device=\"xvda\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Client Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"k6\"}[5m])) by (instance, mode)",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"k6\"} - node_memory_MemFree_bytes{instance=\"k6\"} - node_memory_Buffers_bytes{instance=\"k6\"} - node_memory_Cached_bytes{instance=\"k6\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}