{
 "title": "EDQS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "core_job",
    "label": "Core",
    "query": {
     "query": "label_values(edqsTimers_seconds_count{statsName=\"entityDataQueryTimer\"},job)"
    }
   },
   {
    "name": "edqs_job",
    "label": "EDQS",
    "query": {
     "query": "label_values(edqsGauges{statsName=\"objectsCount\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average data query timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(edqsTimers_seconds_sum{statsName=\"entityDataQueryTimer\", job=~\"$core_job\"}[1m])) * 1000) / sum(rate(edqsTimers_seconds_count{statsName=\"entityDataQueryTimer\", job=~\"$core_job\"}[1m]))",
     "legendFormat": "Query timing"
    },
    {
     "expr": "(sum(rate(edqsTimers_seconds_sum{statsName=\"edqsDataQueryTimer\", job=~\"$edqs_job\"}[1m])) * 1000) / sum(rate(edqsTimers_seconds_count{statsName=\"edqsDataQueryTimer\", job=~\"$edqs_job\"}[1m]))",
     "legendFormat": "EDQS query timing"
    }
   ]
  },
  {
   "title": "Data queries count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(edqsTimers_seconds_count{statsName=\"entityDataQueryTimer\", job=~\"$core_job\"}[1m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Max data query timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(edqsTimers_seconds_max{statsName=\"entityDataQueryTimer\", job=~\"$core_job\"}) * 1000\n",
     "legendFormat": "Query timing"
    },
    {
     "expr": "max(edqsTimers_seconds_max{statsName=\"edqsDataQueryTimer\", job=~\"$edqs_job\"}) * 1000\n",
     "legendFormat": "EDQS query timing"
    }
   ]
  },
  { "title": "Count queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average count query timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(edqsTimers_seconds_sum{statsName=\"entityCountQueryTimer\", job=~\"$core_job\"}[1m])) / sum(rate(edqsTimers_seconds_count{statsName=\"entityCountQueryTimer\", job=~\"$core_job\"}[1m])))*1000\n\n",
     "legendFormat": "Query timing"
    },
    {
     "expr": "(sum(rate(edqsTimers_seconds_sum{statsName=\"edqsCountQueryTimer\", job=~\"$edqs_job\"}[1m])) * 1000) / sum(rate(edqsTimers_seconds_count{statsName=\"edqsCountQueryTimer\", job=~\"$edqs_job\"}[1m]))",
     "legendFormat": "EDQS query timing"
    }
   ]
  },
  {
   "title": "Count queries count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(edqsTimers_seconds_count{statsName=\"entityCountQueryTimer\", job=~\"$core_job\"}[1m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Max count query timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(edqsTimers_seconds_max{statsName=\"entityCountQueryTimer\", job=~\"$core_job\"}) * 1000\n",
     "legendFormat": "Query timing"
    },
    {
     "expr": "max(edqsTimers_seconds_max{statsName=\"edqsCountQueryTimer\", job=~\"$edqs_job\"}) * 1000\n",
     "legendFormat": "EDQS query timing"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=~\"$edqs_job\", id=\"G1 Old Gen\"}",
     "legendFormat": "Used ({{job}})"
    },
    {
     "expr": "jvm_memory_max_bytes{job=~\"$edqs_job\", id=\"G1 Old Gen\"}",
     "legendFormat": "Max ({{job}})"
    }
   ]
  },
  {
   "title": "Objects count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "edqsGauges{statsName=\"objectsCount\", job=~\"$edqs_job\"}",
     "legendFormat": "{{objectType}} ({{job}})"
    }
   ]
  },
  {
   "title": "Pool metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "edqsMapGauges{statsName=\"stringPoolSize\", job=~\"$edqs_job\"}",
     "legendFormat": "String pool size ({{job}})"
    },
    {
     "expr": "edqsMapGauges{statsName=\"bytePoolSize\", job=~\"$edqs_job\"}",
     "legendFormat": "Byte pool size ({{job}})"
    }
   ]
  },
  {
   "title": "Repos",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "edqsMapGauges{statsName=\"tenantReposSize\", job=~\"$edqs_job\"}",
     "legendFormat": "Tenant repos count ({{job}})"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(edqsCounters_total{statsName=\"stringsCompressed\", job=~\"$core_job\"}[1m]))",
     "legendFormat": "Compressed"
    },
    {
     "expr": "sum(increase(edqsCounters_total{statsName=\"stringsUncompressed\", job=~\"$edqs_job\"}[1m]))",
     "legendFormat": "Uncompressed"
    }
   ]
  }
 ]
}