{
 "title": "Hybrid DB Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Attributes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(attributes_queue_0_total[1m]))",
     "legendFormat": "queue-0 {{statsName}}"
    },
    {
     "expr": "sum by(statsName) (increase(attributes_queue_1_total[1m]))",
     "legendFormat": "queue-1 {{statsName}}"
    },
    {
     "expr": "sum by(statsName) (increase(attributes_queue_2_total[1m]))",
     "legendFormat": "queue-2 {{statsName}}"
    },
    {
     "expr": "sum by(statsName) (rate(attributes_queue_3_total[1m]))",
     "legendFormat": "queue-3 {{statsName}}"
    }
   ]
  },
  {
   "title": "Cassandra Current Buffer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (rateExecutor_currBuffer)", "legendFormat": "current buffer" }
   ]
  },
  {
   "title": "TS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statsName) (increase(rateExecutor_total[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "TS Latest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(ts_latest_queue_0_total[1m]))",
     "legendFormat": "queue-0 {{statsName}}"
    },
    {
     "expr": "sum by(statsName) (increase(ts_latest_queue_1_total[1m]))",
     "legendFormat": "queue-1 {{statsName}}"
    },
    {
     "expr": "sum by(statsName) (increase(ts_latest_queue_2_total[1m]))",
     "legendFormat": "queue-2 {{statsName}}"
    },
    {
     "expr": "sum by(statsName) (increase(ts_latest_queue_3_total[1m]))",
     "legendFormat": "queue-3 {{statsName}}"
    }
   ]
  }
 ]
}