{
 "title": "Rule Engine Latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Quantiles Latency, ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job,quantile) (ruleEngine_Main_seconds)*1000",
     "legendFormat": "Main {{job}} Quantile - {{quantile}}, ms"
    },
    {
     "expr": "sum by (job,quantile) (ruleEngine_HighPriority_seconds)*1000",
     "legendFormat": "HighPriority  {{job}} Quantile - {{quantile}}, ms"
    },
    {
     "expr": "sum by (job,quantile) (ruleEngine_SequentialByOriginator_seconds)*1000",
     "legendFormat": "SequentialByOriginator  {{job}} Quantile - {{quantile}}, ms"
    }
   ]
  },
  {
   "title": "Max Latency, ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ruleEngine_Main_seconds_max *1000",
     "legendFormat": "Max - {{job}}, ms"
    },
    {
     "expr": "ruleEngine_HighPriority_seconds_max *1000",
     "legendFormat": "HighPriority - {{job}}, ms"
    },
    {
     "expr": "ruleEngine_SequentialByOriginator_seconds_max *1000",
     "legendFormat": "SequentialByOriginator - {{job}}, ms"
    }
   ]
  },
  {
   "title": "Average by 1m",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(ruleEngine_Main_seconds_sum[1m])  / increase(ruleEngine_Main_seconds_count[1m])) * 1000",
     "legendFormat": "Main  {{job}}"
    },
    {
     "expr": "(increase(ruleEngine_HighPriority_seconds_sum[1m])  / increase(ruleEngine_HighPriority_seconds_count[1m])) * 1000",
     "legendFormat": "HighPriority {{job}}"
    },
    {
     "expr": "(increase(ruleEngine_SequentialByOriginator_seconds_sum[1m])  / increase(ruleEngine_SequentialByOriginator_seconds_count[1m])) * 1000",
     "legendFormat": "SequentialByOriginator {{job}}"
    }
   ]
  }
 ]
}