{
 "title": "Transport Connections",
 "tags": [ "thingsboard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Connections by Protocol",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (protocol) (thingsboard_transport_connections_active{})",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (thingsboard_transport_connections_active)"
    }
   ]
  },
  {
   "title": "Active Connections by Pod",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thingsboard_transport_connections_active",
     "legendFormat": "{{protocol}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Connection Count by Pod",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "expr": "sum by (pod_name) (thingsboard_transport_connections_active)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}