{
 "title": "Transport Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Transport Producer/Consumer Comparison",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(transport_producer_total{statsName=\"totalMsgs\"}[1m]))",
     "legendFormat": "producer"
    },
    {
     "expr": "sum (increase(transport_total{statsName=\"totalMsgs\"}[1m]))",
     "legendFormat": "consumer"
    }
   ]
  },
  {
   "title": "Transport Consumer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(transport_total[1m]))",
     "legendFormat": "{{job}} - {{statsName}}"
    }
   ]
  },
  {
   "title": "Transport Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(transport_producer_total[1m]))",
     "legendFormat": "{{job}} - {{statsName}}"
    }
   ]
  },
  {
   "title": "Core Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(core_producer_total[1m]))",
     "legendFormat": "{{job}} - {{statsName}}"
    }
   ]
  },
  {
   "title": "Rule Engine Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(ruleEngine_producer_total[1m]))",
     "legendFormat": "{{job}} - {{statsName}}"
    }
   ]
  }
 ]
}