{
 "title": "CDC",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Changefeeds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(changefeed_running{scope=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfill Pending Ranges",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node) (changefeed_backfill_pending_ranges{scope=\"\"})",
     "legendFormat": "node={{node}}"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_bytes{scope=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Latencies",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(changefeed_commit_latency_bucket[5m])) by (le))",
     "legendFormat": "p50 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(changefeed_commit_latency_bucket[5m])) by (le))",
     "legendFormat": "p75 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(changefeed_commit_latency_bucket[5m])) by (le))",
     "legendFormat": "p95 {{label_name}}"
    }
   ]
  },
  {
   "title": "Emitted Messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (scope, message_type) (rate(changefeed_emitted_messages{scope!=\"\"}[$__rate_interval]))",
     "legendFormat": "scope={{scope}}, type={{message_type}}"
    }
   ]
  },
  {
   "title": "Failures/Retries/Replans",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by(scope) (changefeed_error_retries{scope!=\"\"})",
     "legendFormat": "retries[scope={{scope}}]"
    },
    {
     "expr": "sum by (scope) (changefeed_error_failures{scope!=\"\"})",
     "legendFormat": "failures[scope={{scope}}]"
    },
    {
     "expr": "sum by (scope) (changefeed_replan_count{scope!=\"\"})",
     "legendFormat": "replans[scope={{scope}}]"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Changefeed Emitted Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{scope=\"\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(node, message_type) (rate(changefeed_emitted_messages{scope!=\"\"}[$__rate_interval]))",
     "legendFormat": "node={{node}}, type={{message_type}}"
    }
   ]
  },
  {
   "title": "Flushed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_flushed_bytes{scope!=\"\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(node) (rate(changefeed_flushed_bytes{scope!=\"\"}[$__rate_interval]))",
     "legendFormat": "node={{node}}"
    }
   ]
  },
  {
   "title": "Frontier Resolved Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(changefeed_frontier_updates[$__rate_interval])*60",
     "legendFormat": "node={{node}}"
    }
   ]
  },
  {
   "title": "Aggregator Resolved Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "rate(changefeed_forwarded_resolved_messages[$__rate_interval])",
     "legendFormat": "node={{node}}"
    }
   ]
  },
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admit Latencies",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(changefeed_admit_latency_bucket[1m])) by (le))",
       "legendFormat": "p50 {{label_name}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(changefeed_admit_latency_bucket[1m])) by (le))",
       "legendFormat": "p75 {{label_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(changefeed_admit_latency_bucket[1m])) by (le))",
       "legendFormat": "p95 {{label_name}}"
      }
     ]
    },
    {
     "title": "Rangefeed Catchup Scan Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum by (node) (irate(kv_rangefeed_catchup_scan_nanos[$__rate_interval]))",
       "legendFormat": "node={{node}}"
      }
     ]
    },
    {
     "title": "SchemaFeed Metadata Wait Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(rate(changefeed_table_metadata_nanos[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Feed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "KVEvent Bytes Buffered",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "changefeed_buffer_entries_mem_acquired - changefeed_buffer_entries_mem_released",
       "legendFormat": "node={{node}}"
      },
      {
       "expr": "sum(changefeed_buffer_entries_mem_acquired - changefeed_buffer_entries_mem_released)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Blocking Buffer Wait Time",
     "type": "timeseries",
     "description": "Time events spent waiting in the kv_feed blocking buffer",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(changefeed_buffer_pushback_nanos[$__rate_interval])",
       "legendFormat": "node={{node}}"
      }
     ]
    },
    {
     "title": "KVEvent Total Queue Time",
     "type": "timeseries",
     "description": "changefeed_queue_time_nanos",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(changefeed_queue_time_nanos[$__rate_interval])",
       "legendFormat": "node={{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Encoding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Consumer Ingest Wait Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(changefeed_nprocs_consume_event_nanos_bucket[$__rate_interval])) by (le))",
       "legendFormat": "p50 {{label_name}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(changefeed_nprocs_consume_event_nanos_bucket[$__rate_interval])) by (le))",
       "legendFormat": "p75 {{label_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(changefeed_nprocs_consume_event_nanos_bucket[$__rate_interval])) by (le))",
       "legendFormat": "p95 {{label_name}}"
      }
     ]
    },
    {
     "title": "Event Consumer Flush Wait Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(changefeed_nprocs_flush_nanos_bucket[$__rate_interval])) by (le))",
       "legendFormat": "p50 {{label_name}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(changefeed_nprocs_flush_nanos_bucket[$__rate_interval])) by (le))",
       "legendFormat": "p75 {{label_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(changefeed_nprocs_flush_nanos_bucket[$__rate_interval])) by (le))",
       "legendFormat": "p95 {{label_name}}"
      }
     ]
    },
    {
     "title": "Event Consumer Inflight Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(changefeed_nprocs_in_flight_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Consumer Buffered Sink Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(changefeed_nprocs_buffered_sink_events_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compression Ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (scope) (changefeed_emitted_bytes{scope!=\"\"}) / sum by (scope) (changefeed_flushed_bytes{scope!=\"\"})",
       "legendFormat": "label={{scope}}"
      }
     ]
    }
   ]
  },
  { "title": "Sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Sink Buffer Time Batched",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(changefeed_sink_batch_hist_nanos_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(changefeed_sink_batch_hist_nanos_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p75 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(changefeed_sink_batch_hist_nanos_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95 {{label_name}}"
    }
   ]
  },
  {
   "title": "Sink Flush Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(changefeed_flush_hist_nanos_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(changefeed_flush_hist_nanos_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p75 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(changefeed_flush_hist_nanos_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95 {{label_name}}"
    }
   ]
  },
  {
   "title": "Sink Flush Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_flushes[$__rate_interval]))",
     "legendFormat": "total_flushes"
    },
    {
     "expr": "sum(rate(changefeed_size_based_flushes[$__rate_interval]))",
     "legendFormat": "size_based_flushes"
    }
   ]
  },
  {
   "title": "Time Spent Checkpointing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(changefeed_checkpoint_hist_nanos_bucket[5m])) by (le))",
     "legendFormat": "p50 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(changefeed_checkpoint_hist_nanos_bucket[5m])) by (le))",
     "legendFormat": "p75 {{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(changefeed_checkpoint_hist_nanos_bucket[5m])) by (le))",
     "legendFormat": "p95 {{label_name}}"
    }
   ]
  },
  {
   "title": "Batches currently in IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(scope) (rate(changefeed_sink_io_inflight{scope!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parallel IO Average Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (scope) ((rate(changefeed_parallel_io_queue_nanos_sum{scope!=\"\"}[5m]) / rate(changefeed_parallel_io_queue_nanos_count{scope!=\"\"}[5m])))",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "description": "sys_cpu_combined_percent_normalized",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sys_cpu_combined_percent_normalized",
       "legendFormat": "node={{node}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Per processor)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cpu, node) (rate(node_cpu_seconds_total{mode != \"idle\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "description": "sys_cpu_combined_percent_normalized",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes",
       "legendFormat": "node={{node}}"
      }
     ]
    },
    {
     "title": "Node Network Bytes Transmit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(node_network_transmit_bytes_total[$__rate_interval]))",
       "legendFormat": "transmit[node={{node}}]"
      }
     ]
    },
    {
     "title": "Node Network Bytes Receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(node_network_receive_bytes_total[$__rate_interval]))",
       "legendFormat": "receive[node={{node}}]"
      }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "KVFeed Buffer Entries In/Out",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "rate(changefeed_buffer_entries_in[$__rate_interval])",
       "legendFormat": "entries_in node={{node}}"
      },
      {
       "expr": "rate(changefeed_buffer_entries_out[$__rate_interval])",
       "legendFormat": "entries_out node={{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Statements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(rate(sql_select_count[$__rate_interval]))",
       "legendFormat": "Selects"
      },
      {
       "expr": "sum(rate(sql_update_count[$__rate_interval]))",
       "legendFormat": "Updates"
      },
      {
       "expr": "sum(rate(sql_insert_count[$__rate_interval]))",
       "legendFormat": "Inserts"
      },
      {
       "expr": "sum(rate(sql_delete_count[$__rate_interval]))",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "SQL Byte Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(sql_bytesin[$__rate_interval]))",
       "legendFormat": "Bytes In"
      },
      {
       "expr": "sum(rate(sql_bytesout[$__rate_interval]))",
       "legendFormat": "Bytes Out"
      }
     ]
    },
    {
     "title": "Service Latency: SQL, 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket[$__rate_interval]))",
       "legendFormat": "node={{node}}"
      }
     ]
    },
    {
     "title": "Service Latency: SQL, 90th percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(sql_service_latency_bucket[$__rate_interval]))",
       "legendFormat": "node={{node}}"
      }
     ]
    }
   ]
  }
 ]
}