{
 "title": "Changefeed Admission Control",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "replicas" } }
  ]
 },
 "panels": [
  { "title": "Elastic CPU limiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elastic CPU utilization limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "admission_elastic_cpu_utilization_limit",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go scheduler latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, node) (rate(go_scheduler_latency_bucket{node=~\"$node\"}[1m])))"
    }
   ]
  },
  {
   "title": "Elastic CPU utilization (smoothed; 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A-$B)/$C", "type": "math" }
   ]
  },
  {
   "title": "Service latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sql_service_latency_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Non-elastic CPU utilization (smoothed; 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$C-(($A-$B))", "type": "math" }
   ]
  },
  {
   "title": "Aggregate CPU utilization (smoothed; 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(sys_cpu_combined_percent_normalized[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average runnable goroutines per CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "goroutines/cpu" } },
   "targets": [
    {
     "expr": "max by(node) (sys_runnable_goroutines_per_cpu{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Aggregate Go scheduler latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(go_scheduler_latency_sum{node=~\"$node\"}[1m])"
    }
   ]
  },
  {
   "title": "CRDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service latency (p99, p99.9)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(sql_service_latency_bucket{node=~\"$node\"}[$__rate_interval])))"
      },
      {
       "expr": "histogram_quantile(0.999, sum by(le) (rate(sql_service_latency_bucket{node=~\"$node\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "SQL statements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(sql_insert_count{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "inserts"
      },
      {
       "expr": "sum(rate(sql_delete_count{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "deletes"
      },
      {
       "expr": "sum(rate(sql_select_count{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "selects"
      },
      {
       "expr": "sum(rate(sql_update_count{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "updates"
      }
     ]
    },
    {
     "title": "Changefeeds running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "changefeed_running", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "replicas{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ranges pending changefeed backfill",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "changefeed_backfill_pending_ranges",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sys_cpu_combined_percent_normalized{node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Changefeed failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(changefeed_failures[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Leaseholders",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "replicas_leaseholders{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Changefeed emitted bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(changefeed_emitted_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# of batch requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "rate(rpc_batches_recv{node=~\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Changefeed emitted messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(changefeed_emitted_messages[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pebble",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memtable flushes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "flushes/sec" } },
     "targets": [
      {
       "expr": "rate(rocksdb_flushes{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memtable flushed bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(rocksdb_flushed_bytes{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read amplification",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rocksdb_read_amplification{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# of compactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "compactions/sec" } },
     "targets": [
      {
       "expr": "rate(rocksdb_compactions{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used disk space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "capacity_used{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LSM ingestions by level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_l6_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(storage_l5_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(storage_l4_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(storage_l3_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(storage_l2_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(storage_l1_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(storage_l0_bytes_ingested{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_written_bytes_total{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Read bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_read_bytes_total{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Log commit latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, node) (rate(raft_process_logcommit_latency_bucket{node=~\"$node\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Compaction bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expression": "$A+$B", "type": "math" }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_writes_completed_total{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(sys_host_disk_read_count{node=~\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Weighted IO time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_io_time_weighted_seconds_total{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "IOPS in progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ios" } },
     "targets": [
      {
       "expr": "sum by(node) (node_disk_io_now{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Estimated pending compaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rocksdb_estimated_pending_compaction{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block cache size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_usage{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Granter total slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "slots" } },
     "targets": [
      {
       "expr": "admission_granter_total_slots_kv{node=~\"$node\"}",
       "legendFormat": "KV {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Granter used slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "slots" } },
     "targets": [
      {
       "expr": "admission_granter_used_slots_kv{node=~\"$node\"}",
       "legendFormat": "KV {node=\"{{node}}\"}"
      },
      {
       "expr": "admission_granter_used_slots_sql_root_start{node=~\"$node\"}",
       "legendFormat": "SQL root start {node=\"{{node}}\"}"
      },
      {
       "expr": "admission_granter_used_slots_sql_leaf_start{node=~\"$node\"}",
       "legendFormat": "SQL leaf start {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "KV admission requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(admission_requested_kv{node=~\"$node\"}[$__rate_interval]))"
      },
      {
       "expr": "sum by() (rate(admission_requested_kv{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "KV requests admitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(admission_admitted_kv{node=~\"$node\"}[$__rate_interval]))"
      },
      {
       "expr": "sum by() (rate(admission_admitted_kv{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "KV stores requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(admission_requested_kv_stores{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{node=\"{{node}}\"}"
      },
      {
       "expr": "sum by() (rate(admission_requested_kv_stores{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "KV stores requests admitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(admission_admitted_kv_stores{node=~\"$node\"}[$__rate_interval]))"
      },
      {
       "expr": "sum by() (rate(admission_admitted_kv_stores{node=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "IO token exhaustion duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(admission_granter_io_tokens_exhausted_duration_kv{node=~\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "KV wait queue length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "admission_wait_queue_length_kv_stores{node=~\"$node\"}",
       "legendFormat": "KV stores {node=\"{{node}}\"}"
      },
      {
       "expr": "admission_wait_queue_length_kv{node=~\"$node\"}",
       "legendFormat": "KV {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Aggregate wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(admission_wait_durations_kv_stores_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "KV stores {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_durations_kv_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "KV {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_durations_sql_kv_response_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "SQL-KV {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_durations_sql_sql_response_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "SQL-SQL {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_durations_sql_leaf_start_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "SQL leaf start {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_durations_sql_root_start_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "SQL root start {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_durations_elastic_cpu_sum{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "Elastic CPU {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Queue wait durations (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_kv_bucket{node=~\"$node\"}[$__rate_interval])) by (le))",
       "legendFormat": "KV"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_kv_stores_bucket{node=~\"$node\"}[$__rate_interval])) by (le))",
       "legendFormat": "KV Stores"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_kv_response_bucket{node=~\"$node\"}[$__rate_interval])) by (le))",
       "legendFormat": "SQL-KV"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_sql_response_bucket{node=~\"$node\"}[$__rate_interval])) by (le))",
       "legendFormat": "SQL-SQL"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_leaf_start_bucket{node=~\"$node\"}[$__rate_interval])) by (le)) ",
       "legendFormat": "SQL leaf start"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_root_start_bucket{node=~\"$node\"}[$__rate_interval])) by (le)) ",
       "legendFormat": "SQL root start"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(admission_wait_durations_elastic_cpu_bucket{node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "Elastic CPU"
      }
     ]
    },
    {
     "title": "IO Admission Threshold Fraction",
     "type": "timeseries",
     "description": "at 1, IO admission control kicks in",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "admission_io_overload{node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "L0 flushed + ingested bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(storage_l0_bytes_ingested{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "ingested {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(storage_l0_bytes_flushed{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "flushed {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Elastic CPU utilization limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "admission_elastic_cpu_utilization_limit{node=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PSI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Stalled PSI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_pressure_io_stalled_seconds_total{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "n{{node}}"
      }
     ]
    },
    {
     "title": "CPU PSI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_pressure_cpu_waiting_seconds_total{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "cpu-psi-n{{node}}"
      }
     ]
    },
    {
     "title": "IO Waiting PSI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_pressure_io_waiting_seconds_total{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "n{{node}}"
      }
     ]
    }
   ]
  }
 ]
}