{
 "title": "Multi-tenant Fairness Admission Control",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant_sql_metrics", "label": "Tenant SQL Metrics", "query": { "query": "sql_update_count" } },
   { "name": "tenant_kv_metrics", "label": "Tenant KV Metrics", "query": { "query": "livebytes" } },
   { "name": "kv_metrics", "label": "KV Metrics", "query": { "query": "replicas" } }
  ]
 },
 "panels": [
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(workload_kv_read_duration_seconds_count[$__rate_interval])",
     "legendFormat": "Reads ({{job}})"
    }
   ]
  },
  {
   "title": "Read latencies (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workload_kv_read_duration_seconds_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "Reads p99 ({{job}})"
    }
   ]
  },
  {
   "title": "Write ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(workload_kv_write_duration_seconds_count[$__rate_interval])",
     "legendFormat": "Reads ({{job}})"
    }
   ]
  },
  {
   "title": "Write latencies (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workload_kv_read_duration_seconds_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "Reads p99 ({{job}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workload_kv_write_duration_seconds_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "Write p99 ({{job}})"
    }
   ]
  },
  { "title": "Tenant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Write bytes admitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kv_tenant_rate_limit_write_bytes_admitted{\n    tenant_id !=\"\",\n    tenant_id =~ \"$tenant_kv_metrics\",\n}[$__rate_interval])",
     "legendFormat": "Tenant = {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Write batches admitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kv_tenant_rate_limit_write_batches_admitted{\n    tenant_id !=\"\",\n    tenant_id =~ \"$tenant_kv_metrics\",\n}[$__rate_interval])",
     "legendFormat": "Tenant = {{tenant_id}}"
    }
   ]
  },
  {
   "title": "KV RUs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tenant_consumption_kv_request_units{\n    tenant_id !=\"\",\n    tenant_id =~ \"$tenant_kv_metrics\",\n}[$__rate_interval])",
     "legendFormat": "Tenant = {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Read bytes admitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kv_tenant_rate_limit_read_bytes_admitted{\n    tenant_id !=\"\",\n    tenant_id =~ \"$tenant_kv_metrics\",\n}[$__rate_interval])",
     "legendFormat": "Tenant = {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Read batches admitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kv_tenant_rate_limit_read_batches_admitted{\n    tenant_id !=\"\",\n    tenant_id =~ \"$tenant_kv_metrics\",\n}[$__rate_interval])",
     "legendFormat": "Tenant = {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "totalbytes{\n    tenant_id !=\"\",\n    tenant_id =~ \"$tenant_kv_metrics\",\n}",
     "legendFormat": "Tenant = {{tenant_id}}"
    }
   ]
  },
  { "title": "CRDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Service latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,tenant) (rate(sql_service_latency_bucket{\n    tenant=~\"$tenant_sql_metrics\",\n}[$__rate_interval])))",
     "legendFormat": "SQL p99 (tenant {{tenant}})"
    }
   ]
  },
  {
   "title": "SQL statements (updates and selects)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(sql_update_count{\n    tenant=~\"$tenant_sql_metrics\",\n}[$__rate_interval]))",
     "legendFormat": "Updates (tenant {{tenant}})"
    },
    {
     "expr": "sum by (tenant) (rate(sql_select_count{\n    tenant=~\"$tenant_sql_metrics\",\n}[$__rate_interval]))",
     "legendFormat": "Selects (tenant {{tenant}})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "replicas{node=~\"$kv_metrics\"}",
     "legendFormat": "Node: {{node}}"
    }
   ]
  },
  {
   "title": "Leaseholders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "expr": "replicas_leaseholders{node=~\"$kv_metrics\"}",
     "legendFormat": "Node: {{node}}"
    }
   ]
  },
  {
   "title": "SQL statements (inserts and deletes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(sql_insert_count{\n    tenant=~\"$tenant_sql_metrics\",\n}[$__rate_interval]))",
     "legendFormat": "Inserts (tenant {{tenant}})"
    },
    {
     "expr": "sum by (tenant) (rate(sql_delete_count{\n    tenant=~\"$tenant_sql_metrics\",\n}[$__rate_interval]))",
     "legendFormat": "Deletes (tenant {{tenant}})"
    }
   ]
  },
  {
   "title": "# of batch requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(rpc_batches_recv{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "Node: {{node}}"
    }
   ]
  },
  { "title": "Admission Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "IO Admission Threshold Fraction",
   "type": "timeseries",
   "description": "at 1, IO admission control kicks in",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "admission_io_overload{node=~\"$kv_metrics\"}"
    }
   ]
  },
  {
   "title": "Elastic CPU utilization and limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "admission_elastic_cpu_utilization_limit{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "admission_elastic_cpu_utilization{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue wait durations (p99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_kv_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "KV"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_kv_stores_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "KV Stores"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_kv_response_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "SQL-KV"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_sql_response_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "SQL-SQL"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_leaf_start_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "SQL leaf start"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_root_start_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "SQL root start"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(admission_wait_durations_elastic_cpu_bucket{node=~\"$kv_metrics\"}[$__rate_interval])))",
     "legendFormat": "Elastic CPU"
    }
   ]
  },
  {
   "title": "IO token exhaustion duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(admission_granter_io_tokens_exhausted_duration_kv{node=~\"$kv_metrics\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Queue wait durations (p75)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(admission_wait_durations_kv_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "KV"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(admission_wait_durations_kv_stores_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "KV Stores"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(admission_wait_durations_sql_kv_response_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "SQL-KV"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(admission_wait_durations_sql_sql_response_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "SQL-SQL"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_leaf_start_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "SQL leaf start"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_root_start_bucket{node=~\"$kv_metrics\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "SQL root start"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(admission_wait_durations_elastic_cpu_bucket{node=~\"$kv_metrics\"}[$__rate_interval])))",
     "legendFormat": "Elastic CPU"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_cpu_combined_percent_normalized{\n    tenant=~\"$tenant_sql_metrics\",\n}",
     "legendFormat": "Node: {{node}} ({{job}})"
    },
    {
     "expr": "sys_cpu_combined_percent_normalized{\n    node=~\"$kv_metrics\",\n}",
     "legendFormat": "Node: {{node}} ({{job}})"
    }
   ]
  },
  {
   "title": "Aggregate wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(admission_wait_durations_kv_stores_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "KV stores {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(admission_wait_durations_kv_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "KV {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(admission_wait_durations_sql_kv_response_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "SQL-KV {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(admission_wait_durations_sql_sql_response_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "SQL-SQL {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(admission_wait_durations_sql_leaf_start_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "SQL leaf start {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(admission_wait_durations_sql_root_start_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "SQL root start {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(admission_wait_durations_elastic_cpu_sum{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "Elastic CPU {node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "KV admission requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(admission_requested_kv{node=~\"$kv_metrics\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by() (rate(admission_requested_kv{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "KV requests admitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(admission_admitted_kv{node=~\"$kv_metrics\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by() (rate(admission_admitted_kv{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "KV, KV-Stores wait queue length",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "admission_wait_queue_length_kv_stores{node=~\"$kv_metrics\"}",
     "legendFormat": "KV stores {node=\"{{node}}\"}"
    },
    {
     "expr": "admission_wait_queue_length_kv{node=~\"$kv_metrics\"}",
     "legendFormat": "KV {node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "KV stores requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(admission_requested_kv_stores{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "{node=\"{{node}}\"}"
    },
    {
     "expr": "sum by() (rate(admission_requested_kv_stores{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "KV stores requests admitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(admission_admitted_kv_stores{node=~\"$kv_metrics\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by() (rate(admission_admitted_kv_stores{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "L0 flushed + ingested bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(storage_l0_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "ingested {node=\"{{node}}\"}"
    },
    {
     "expr": "rate(storage_l0_bytes_flushed{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "flushed {node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Granter total slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "admission_granter_total_slots_kv{node=~\"$kv_metrics\"}",
     "legendFormat": "KV {node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Granter used slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "admission_granter_used_slots_kv{node=~\"$kv_metrics\"}",
     "legendFormat": "KV {node=\"{{node}}\"}"
    },
    {
     "expr": "admission_granter_used_slots_sql_root_start{node=~\"$kv_metrics\"}",
     "legendFormat": "SQL root start {node=\"{{node}}\"}"
    },
    {
     "expr": "admission_granter_used_slots_sql_leaf_start{node=~\"$kv_metrics\"}",
     "legendFormat": "SQL leaf start {node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Average runnable goroutines per CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "goroutines/cpu" } },
   "targets": [
    {
     "expr": "max by(node) (sys_runnable_goroutines_per_cpu{node=~\"$kv_metrics\"})"
    }
   ]
  },
  { "title": "Go scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Go scheduler latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, node) (rate(go_scheduler_latency_bucket{node=~\"$kv_metrics\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Aggregate Go scheduler latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(go_scheduler_latency_sum{node=~\"$kv_metrics\"}[1m])"
    }
   ]
  },
  {
   "title": "# of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sys_goroutines{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pebble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "L0 file count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "storage_l0_num_files{node=~\"$kv_metrics\"}",
     "legendFormat": "Store: {{store}} (node {{node}})"
    }
   ]
  },
  {
   "title": "L0 sublevels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 116 },
   "targets": [
    {
     "expr": "storage_l0_sublevels{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtable flushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "flushes/sec" } },
   "targets": [
    {
     "expr": "rate(rocksdb_flushes{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtable flushed bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(rocksdb_flushed_bytes{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL fsync latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, node) (rate(storage_wal_fsync_latency_bucket{node=~\"$kv_metrics\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(node_disk_read_bytes_total{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Log commit latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, node) (rate(raft_process_logcommit_latency_bucket{node=~\"$kv_metrics\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(node_disk_written_bytes_total{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Compaction bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Read amplification",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "rocksdb_read_amplification{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(node_disk_writes_completed_total{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_read_count{node=~\"$kv_metrics\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "# of compactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "compactions/sec" } },
   "targets": [
    {
     "expr": "rate(rocksdb_compactions{node=~\"$kv_metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated pending compaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rocksdb_estimated_pending_compaction{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS in progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "ios" } },
   "targets": [
    {
     "expr": "sum by(node) (node_disk_io_now{node=~\"$kv_metrics\"})"
    }
   ]
  },
  {
   "title": "LSM ingestions by level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(storage_l6_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_l5_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_l4_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_l3_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_l2_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_l1_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_l0_bytes_ingested{node=~\"$kv_metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weighted IO time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(node_disk_io_time_weighted_seconds_total{node=~\"$kv_metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Block cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rocksdb_block_cache_usage{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used disk space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "capacity_used{node=~\"$kv_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}